import {
  createField,
  createSection,
  createSubmission,
  createTemplate,
  deleteField,
  deleteSection,
  deleteTemplate,
  getSubmissionById,
  getTemplateById,
  getTemplateBySlug,
  listFieldsBySectionId,
  listSectionsByTemplateId,
  listSubmissions,
  listTemplates,
  reorderFields,
  reorderSections,
  updateField,
  updateSection,
  updateTemplate,
} from "@/infra/repositories/laudosRepository";

export const laudosService = {
  listTemplates,
  getTemplateById,
  getTemplateBySlug,
  createTemplate,
  updateTemplate,
  deleteTemplate,
  createSection,
  listSectionsByTemplateId,
  updateSection,
  deleteSection,
  reorderSections,
  createField,
  listFieldsBySectionId,
  updateField,
  deleteField,
  reorderFields,
  createSubmission,
  listSubmissions,
  getSubmissionById,
};
